"""empty message

Revision ID: 1578cff1c968
Revises: cb0b0be60c06
Create Date: 2022-06-02 16:54:43.391700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1578cff1c968'
down_revision = 'cb0b0be60c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
